.TH "/home/shaan/Desktop/Computer Science/Sync/inc Directory Reference" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClient\&.h\fP"
.br
.ti -1c
.RI "file \fBError\&.h\fP"
.br
.ti -1c
.RI "file \fBGroup\&.h\fP"
.br
.ti -1c
.RI "file \fBjson\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMember\&.h\fP"
.br
.ti -1c
.RI "file \fBMessage\&.h\fP"
.br
.ti -1c
.RI "file \fBServer\&.h\fP"
.br
.in -1c
