.TH "/home/shaan/Desktop/Computer Science/Sync/src Directory Reference" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBError\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGroup\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMember\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMessage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBServer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBserver_main\&.cpp\fP"
.br
.in -1c
