.TH "/home/shaan/Desktop/Computer Science/Sync/inc/Client.h" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/inc/Client.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Group\&.h'\fP
.br
\fC#include 'Error\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBshaan97::sync::Client\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBshaan97\fP"
.br
.RI "The namespace for the github user \fBshaan97\fP\&. "
.ti -1c
.RI " \fBshaan97::sync\fP"
.br
.RI "The namespace for the sync project\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
