.TH "/home/shaan/Desktop/Computer Science/Sync/src/Client.cpp" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/src/Client.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/Client\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <future>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <exception>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
