.TH "ErrorReporting" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorReporting
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBshaan97::sync::Server::sendFailure\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, const \fBError\fP &error)"
.br
.ti -1c
.RI "static void \fBshaan97::sync::Server::sendSuccess\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket)"
.br
.ti -1c
.RI "static void \fBshaan97::sync::Server::sendSuccess\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, const \fBError\fP &error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These functions report success or failure across the socket, (potentially) based upon the value of the \fC\fBshaan97::sync::Error\fP\fP object\&. 
.SH "Function Documentation"
.PP 
.SS "void Server::sendFailure (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, const \fBError\fP & error)\fC [static]\fP, \fC [private]\fP"

.SS "void Server::sendSuccess (std::shared_ptr< boost::asio::ip::tcp::socket > & socket)\fC [static]\fP, \fC [private]\fP"

.SS "void Server::sendSuccess (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, const \fBError\fP & error)\fC [static]\fP, \fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
