.TH "/home/shaan/Desktop/Computer Science/Sync/inc/Error.h" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/inc/Error.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include 'json\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBshaan97::sync::Error\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBshaan97\fP"
.br
.RI "The namespace for the github user \fBshaan97\fP\&. "
.ti -1c
.RI " \fBshaan97::sync\fP"
.br
.RI "The namespace for the sync project\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBshaan97::sync::ERROR_TYPE\fP { \fBshaan97::sync::NONE\fP = 0, \fBshaan97::sync::FAILED_CONNECTION\fP, \fBshaan97::sync::GID_EXISTS\fP, \fBshaan97::sync::GID_NO_EXIST\fP, \fBshaan97::sync::OTHER\fP, \fBshaan97::sync::ACCESS_DENIED\fP, \fBshaan97::sync::CORRUPTED_DATA\fP, \fBshaan97::sync::MEMBER_EXISTS\fP, \fBshaan97::sync::MEMBER_NO_EXIST\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBshaan97::sync::operator<<\fP (std::ostream &out, const \fBError\fP &e)"
.br
.ti -1c
.RI "void \fBshaan97::sync::to_json\fP (\fBnlohmann::json\fP &j, const \fBError\fP &e)"
.br
.ti -1c
.RI "void \fBshaan97::sync::from_json\fP (\fBnlohmann::json\fP &j, \fBError\fP &e)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
