.TH "/home/shaan/Desktop/Computer Science/Sync/src/Error.cpp" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/src/Error.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/Error\&.h'\fP
.br
\fC#include '\&.\&./inc/Message\&.h'\fP
.br
\fC#include <sstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBerrorToString\fP (const \fBERROR_TYPE\fP &error)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string errorToString (const \fBERROR_TYPE\fP & error)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
