.TH "/home/shaan/Desktop/Computer Science/Sync/src/Group.cpp" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/src/Group.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/Group\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
