.TH "/home/shaan/Desktop/Computer Science/Sync/inc/Group.h" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/inc/Group.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Member\&.h'\fP
.br
\fC#include 'Error\&.h'\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBshaan97::sync::Group\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBshaan97\fP"
.br
.RI "The namespace for the github user \fBshaan97\fP\&. "
.ti -1c
.RI " \fBshaan97::sync\fP"
.br
.RI "The namespace for the sync project\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::string \fBshaan97::sync::GROUP_ID\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
