.TH "/home/shaan/Desktop/Computer Science/Sync/src/Member.cpp" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/src/Member.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/Member\&.h'\fP
.br
\fC#include '\&.\&./inc/Message\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBto_json\fP (\fBnlohmann::json\fP &j, const \fBMember\fP &m)"
.br
.ti -1c
.RI "void \fBfrom_json\fP (\fBnlohmann::json\fP &j, \fBMember\fP &m)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
