.TH "MessageHandling" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageHandling
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBshaan97::sync::Server::createGroup\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, \fBMessage\fP &message)"
.br
.ti -1c
.RI "void \fBshaan97::sync::Server::addToGroup\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, \fBMessage\fP &message)"
.br
.ti -1c
.RI "void \fBshaan97::sync::Server::deleteGroup\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, \fBMessage\fP &message)"
.br
.ti -1c
.RI "void \fBshaan97::sync::Server::handle_heartbeat\fP (\fBMessage\fP &heartbeat)"
.br
.ti -1c
.RI "void \fBshaan97::sync::Server::promoteMember\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, \fBMessage\fP &message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These functions provide the various services that a client can request to the \fBServer\fP These will report success or failure across the socket asynchronously\&. 
.SH "Function Documentation"
.PP 
.SS "void Server::addToGroup (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, \fBMessage\fP & message)\fC [private]\fP"

.SS "void Server::createGroup (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, \fBMessage\fP & message)\fC [private]\fP"

.SS "void Server::deleteGroup (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, \fBMessage\fP & message)\fC [private]\fP"

.SS "void Server::handle_heartbeat (\fBMessage\fP & heartbeat)\fC [private]\fP"

.SS "void Server::promoteMember (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, \fBMessage\fP & message)\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
