.TH "/home/shaan/Desktop/Computer Science/Sync/inc/Message.h" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/inc/Message.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include 'Member\&.h'\fP
.br
\fC#include 'Group\&.h'\fP
.br
\fC#include 'json\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBshaan97::sync::Message\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBshaan97\fP"
.br
.RI "The namespace for the github user \fBshaan97\fP\&. "
.ti -1c
.RI " \fBshaan97::sync\fP"
.br
.RI "The namespace for the sync project\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBshaan97::sync::MessageType\fP { \fBshaan97::sync::GROUP_JOIN\fP = 0, \fBshaan97::sync::GROUP_CREATE\fP, \fBshaan97::sync::HEARTBEAT\fP, \fBshaan97::sync::GROUP_EXIT\fP, \fBshaan97::sync::PROMOTE\fP, \fBshaan97::sync::ERROR\fP }"
.br
.ti -1c
.RI "enum \fBshaan97::sync::JSON_KEY\fP { \fBshaan97::sync::TYPE\fP = 0, \fBshaan97::sync::MEMBER\fP, \fBshaan97::sync::GID\fP, \fBshaan97::sync::OTHER_MEM\fP, \fBshaan97::sync::NAME\fP, \fBshaan97::sync::ERROR_MESSAGE\fP, \fBshaan97::sync::DETAILS\fP, \fBshaan97::sync::SYNC_ERROR\fP, \fBshaan97::sync::BOOST_ERROR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBshaan97::sync::to_json\fP (\fBnlohmann::json\fP &j, const \fBMessage\fP &m)"
.br
.RI "Converts a \fC\fBMessage\fP\fP into a \fC\fBnlohmann::json\fP object\fP "
.ti -1c
.RI "void \fBshaan97::sync::from_json\fP (\fBnlohmann::json\fP &j, \fBMessage\fP &m)"
.br
.RI "Converts a \fC\fBnlohmann::json\fP\fP into a \fC\fBMessage\fP\fP object\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
