.TH "nlohmann::detail::external_constructor< value_t::number_integer >" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::number_integer >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > static void \fBconstruct\fP (BasicJsonType &j, typename BasicJsonType::number_integer_t val) noexcept"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType > static void \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::number_integer\fP >::construct (BasicJsonType & j, typename BasicJsonType::number_integer_t val)\fC [inline]\fP, \fC [static]\fP, \fC [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
