.TH "nlohmann::detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_integer_type< RealIntegerType, CompatibleNumberIntegerType >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr auto \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename RealIntegerType , typename CompatibleNumberIntegerType > constexpr auto \fBnlohmann::detail::is_compatible_integer_type\fP< RealIntegerType, CompatibleNumberIntegerType >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
=
        is_compatible_integer_type_impl <
        std::is_integral<CompatibleNumberIntegerType>::value and
        not std::is_same<bool, CompatibleNumberIntegerType>::value,
        RealIntegerType, CompatibleNumberIntegerType > ::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
