.TH "nlohmann" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann \- namespace for Niels Lohmann  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdetail\fP"
.br
.RI "unnamed namespace with internal helper functions "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBadl_serializer\fP"
.br
.RI "default JSONSerializer template argument "
.ti -1c
.RI "class \fBbasic_json\fP"
.br
.RI "a class to store JSON values "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = \fBbasic_json\fP<>"
.br
.RI "default JSON class "
.in -1c
.SH "Detailed Description"
.PP 
namespace for Niels Lohmann 


.PP
\fBSee also:\fP
.RS 4
https://github.com/nlohmann 
.RE
.PP
\fBSince:\fP
.RS 4
version 1\&.0\&.0 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "using \fBnlohmann::json\fP = typedef \fBbasic_json\fP<>"

.PP
default JSON class This type is the default specialization of the \fBbasic_json\fP class which uses the standard template types\&.
.PP
\fBSince:\fP
.RS 4
version 1\&.0\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
