.TH "nlohmann::detail::is_compatible_integer_type_impl< bool, typename, typename >" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_compatible_integer_type_impl< bool, typename, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.PP
Inherits false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
