.TH "nlohmann::detail::external_constructor< value_t::object >" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::external_constructor< value_t::object >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename BasicJsonType > static void \fBconstruct\fP (BasicJsonType &j, const typename BasicJsonType::object_t &obj)"
.br
.ti -1c
.RI "template<typename BasicJsonType , typename CompatibleObjectType , enable_if_t< not std::is_same< CompatibleObjectType, typename BasicJsonType::object_t >::value, int >  = 0> static void \fBconstruct\fP (BasicJsonType &j, const CompatibleObjectType &obj)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename BasicJsonType > static void \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::object\fP >::construct (BasicJsonType & j, const typename BasicJsonType::object_t & obj)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename BasicJsonType , typename CompatibleObjectType , enable_if_t< not std::is_same< CompatibleObjectType, typename BasicJsonType::object_t >::value, int >  = 0> static void \fBnlohmann::detail::external_constructor\fP< \fBvalue_t::object\fP >::construct (BasicJsonType & j, const CompatibleObjectType & obj)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
