.TH "nlohmann::detail::is_basic_json_nested_type< BasicJsonType, T >" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nlohmann::detail::is_basic_json_nested_type< BasicJsonType, T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static auto constexpr \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename BasicJsonType , typename T > auto constexpr \fBnlohmann::detail::is_basic_json_nested_type\fP< BasicJsonType, T >::value\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= std::is_same<T, typename BasicJsonType::iterator>::value or
                                  std::is_same<T, typename BasicJsonType::const_iterator>::value or
                                  std::is_same<T, typename BasicJsonType::reverse_iterator>::value or
                                  std::is_same<T, typename BasicJsonType::const_reverse_iterator>::value or
                                  std::is_same<T, typename BasicJsonType::json_pointer>::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
