.TH "Serialization" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serialization
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBshaan97::sync::to_json\fP (\fBnlohmann::json\fP &j, const \fBMember\fP &m)"
.br
.ti -1c
.RI "void \fBshaan97::sync::from_json\fP (\fBnlohmann::json\fP &j, \fBMember\fP &m)"
.br
.ti -1c
.RI "void \fBshaan97::sync::to_json\fP (\fBnlohmann::json\fP &j, const \fBMessage\fP &m)"
.br
.RI "Converts a \fC\fBMessage\fP\fP into a \fC\fBnlohmann::json\fP object\fP "
.ti -1c
.RI "void \fBshaan97::sync::from_json\fP (\fBnlohmann::json\fP &j, \fBMessage\fP &m)"
.br
.RI "Converts a \fC\fBnlohmann::json\fP\fP into a \fC\fBMessage\fP\fP object\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "void \fBshaan97::sync::Error::to_json\fP (\fBnlohmann::json\fP &j, const \fBError\fP &e)"
.br
.ti -1c
.RI "void \fBshaan97::sync::Error::from_json\fP (\fBnlohmann::json\fP &j, \fBError\fP &e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These are JSON helper functions that help in the serialization of \fCMessages\fP\&. 
.SH "Function Documentation"
.PP 
.SS "void shaan97::sync::from_json (\fBnlohmann::json\fP & j, \fBMessage\fP & m)"

.PP
Converts a \fC\fBnlohmann::json\fP\fP into a \fC\fBMessage\fP\fP object\&. 
.SS "void shaan97::sync::from_json (\fBnlohmann::json\fP & j, \fBMember\fP & m)"
Converts a \fCnlohmann:json\fP into a \fC\fBMember\fP\fP 
.SS "void shaan97::sync::to_json (\fBnlohmann::json\fP & j, const \fBMessage\fP & m)"

.PP
Converts a \fC\fBMessage\fP\fP into a \fC\fBnlohmann::json\fP object\fP 
.SS "void shaan97::sync::to_json (\fBnlohmann::json\fP & j, const \fBMember\fP & m)"
Converts a \fC\fBMember\fP\fP into a \fC\fBnlohmann::json\fP\fP 
.SH "Friends"
.PP 
.SS "void from_json (\fBnlohmann::json\fP & j, \fBError\fP & e)\fC [friend]\fP"
Converts from \fC\fBnlohmann::json\fP\fP to a \fC\fBError\fP\fP object 
.SS "void to_json (\fBnlohmann::json\fP & j, const \fBError\fP & e)\fC [friend]\fP"
Converts from \fC\fBError\fP\fP to a \fC\fBnlohmann::json\fP\fP object 
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
