.TH "/home/shaan/Desktop/Computer Science/Sync/src/Server.cpp" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/src/Server.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./inc/Server\&.h'\fP
.br
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <future>\fP
.br
\fC#include '\&.\&./inc/json\&.hpp'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = \fBnlohmann::json\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMessage\fP \fBinterpret_socket\fP (std::shared_ptr< boost::asio::ip::tcp::socket > &socket, \fBError\fP &e)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBjson\fP =  \fBnlohmann::json\fP"

.SH "Function Documentation"
.PP 
.SS "\fBMessage\fP interpret_socket (std::shared_ptr< boost::asio::ip::tcp::socket > & socket, \fBError\fP & e)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
