.TH "/home/shaan/Desktop/Computer Science/Sync/inc/Server.h" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/shaan/Desktop/Computer Science/Sync/inc/Server.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include 'Group\&.h'\fP
.br
\fC#include 'Member\&.h'\fP
.br
\fC#include 'Message\&.h'\fP
.br
\fC#include <mutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBshaan97::sync::Server\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBshaan97\fP"
.br
.RI "The namespace for the github user \fBshaan97\fP\&. "
.ti -1c
.RI " \fBshaan97::sync\fP"
.br
.RI "The namespace for the sync project\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_VERSION\fP   boost::asio::ip::tcp::v4()"
.br
.ti -1c
.RI "#define \fBDEFAULT_PORT\fP   13"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_PORT   13"

.SS "#define DEFAULT_VERSION   boost::asio::ip::tcp::v4()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
