.TH "shaan97" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shaan97 \- The namespace for the github user \fBshaan97\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsync\fP"
.br
.RI "The namespace for the sync project\&. "
.in -1c
.SH "Detailed Description"
.PP 
The namespace for the github user \fBshaan97\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
