.TH "std::hash< nlohmann::json >" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::hash< nlohmann::json > \- hash value for JSON objects  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::size_t \fBoperator()\fP (const \fBnlohmann::json\fP &j) const"
.br
.RI "return a hash value for a JSON object "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
struct std::hash< nlohmann::json >"
hash value for JSON objects 
.SH "Member Function Documentation"
.PP 
.SS "std::size_t std::hash< \fBnlohmann::json\fP >::operator() (const \fBnlohmann::json\fP & j) const\fC [inline]\fP"

.PP
return a hash value for a JSON object 
.PP
\fBSince:\fP
.RS 4
version 1\&.0\&.0 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
