.TH "sync" 3 "Wed Jul 12 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sync \- The namespace for the sync project\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
The namespace for the sync project\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
