.TH "SyntacticSugar" 3 "Tue Jul 18 2017" "Version 1.0.0" "Sync" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyntacticSugar
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBshaan97::sync::Error::operator==\fP (const \fBError\fP &e)"
.br
.ti -1c
.RI "bool \fBshaan97::sync::Error::operator==\fP (const \fBERROR_TYPE\fP &e)"
.br
.ti -1c
.RI "bool \fBshaan97::sync::Error::operator==\fP (const boost::system::error_code &e)"
.br
.ti -1c
.RI "bool \fBshaan97::sync::Error::operator!=\fP (const \fBError\fP &e)"
.br
.ti -1c
.RI "bool \fBshaan97::sync::Error::operator!=\fP (const \fBERROR_TYPE\fP &e)"
.br
.ti -1c
.RI "bool \fBshaan97::sync::Error::operator!=\fP (const boost::system::error_code &e)"
.br
.ti -1c
.RI "\fBshaan97::sync::Error::operator bool\fP () const"
.br
.RI "True if there was an error\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBshaan97::sync::Error::operator<<\fP (std::ostream &out, const \fBError\fP &e)"
.br
.RI "Can be used to send formatted string to ostream\&. "
.in -1c
.SH "Detailed Description"
.PP 
Various operator overloads that make code look cleaner 
.SH "Function Documentation"
.PP 
.SS "Error::operator bool () const"

.PP
True if there was an error\&. 
.SS "bool Error::operator!= (const \fBError\fP & e)"

.SS "bool Error::operator!= (const \fBERROR_TYPE\fP & e)"

.SS "bool Error::operator!= (const boost::system::error_code & e)"

.SS "bool Error::operator== (const \fBError\fP & e)"

.SS "bool Error::operator== (const \fBERROR_TYPE\fP & e)"

.SS "bool Error::operator== (const boost::system::error_code & e)"

.SH "Friends"
.PP 
.SS "std::ostream& operator<< (std::ostream & out, const \fBError\fP & e)\fC [friend]\fP"

.PP
Can be used to send formatted string to ostream\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Sync from the source code\&.
